# Generated by Django 5.1 on 2024-08-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_historico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historico',
        ),
    ]
