# Generated by Django 5.1 on 2024-08-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0003_delete_historico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rotten_tomatoes',
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
