# Generated by Django 5.1 on 2024-08-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0004_remove_movie_created_at_remove_movie_rotten_tomatoes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ano', models.CharField(max_length=10)),
                ('diretor', models.CharField(max_length=255)),
                ('sinopse', models.TextField()),
                ('url_poster', models.URLField()),
                ('avaliacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
